// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSu_mKlGbq6H0RTuLnhUIKF_bV7ba7QxU',
    appId: '1:520901543892:web:804bb55f7ed4079345b841',
    messagingSenderId: '520901543892',
    projectId: 'firetask-2e332',
    authDomain: 'firetask-2e332.firebaseapp.com',
    storageBucket: 'firetask-2e332.appspot.com',
    measurementId: 'G-3MEGJTN1D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD03RYmpS__fMvMbtkrnkxjaaeXGGy1sI0',
    appId: '1:520901543892:android:36bf31998cdff43e45b841',
    messagingSenderId: '520901543892',
    projectId: 'firetask-2e332',
    storageBucket: 'firetask-2e332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBblWdjJovlQyLZiYMVVMRSqkV17Utg6Ws',
    appId: '1:520901543892:ios:5ca723fe8fe8f8bf45b841',
    messagingSenderId: '520901543892',
    projectId: 'firetask-2e332',
    storageBucket: 'firetask-2e332.appspot.com',
    iosClientId: '520901543892-o4m96adu0pk63k2j0dmslbe3aja9f407.apps.googleusercontent.com',
    iosBundleId: 'com.example.firetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBblWdjJovlQyLZiYMVVMRSqkV17Utg6Ws',
    appId: '1:520901543892:ios:5ca723fe8fe8f8bf45b841',
    messagingSenderId: '520901543892',
    projectId: 'firetask-2e332',
    storageBucket: 'firetask-2e332.appspot.com',
    iosClientId: '520901543892-o4m96adu0pk63k2j0dmslbe3aja9f407.apps.googleusercontent.com',
    iosBundleId: 'com.example.firetask',
  );
}
